apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oxisentinel-gateway-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oxisentinel-gateway-controller.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oxisentinel-gateway-controller.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oxisentinel-gateway-controller.name" . }}
    spec:
      serviceAccountName: {{ default (include "oxisentinel-gateway-controller.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
